#!/usr/bin/env python3

# MIT License
#
# Group re-implementation of the stitching step (assignment 03), replacing the
# original script by Hoel Kervadec. Reconstructs 3D NIfTI volumes from the 2D
# prediction slices saved as .png by main.py / infer.py.
#
# Differences from the original:
# * absent classes are allowed (part-1 data has no aorta label);
# * geometry (shape, affine, header) is taken from the CT scan, which carries
#   the true voxel spacing, and not from the GT file whose affine is identity;
# * the label encoding of the .png is derived from the number of classes, the
#   same way main.py encodes it, instead of a hardcoded division by 63;
# * optional multiprocessing, one patient per process.
# * Inverse spatial sampling process

import re
import argparse
from pathlib import Path
from functools import partial
from multiprocessing import Pool
from typing import Match, Pattern

import numpy as np
import nibabel as nib
import scipy.ndimage
from skimage.io import imread
from skimage.transform import resize

from utils import map_, tqdm_


def label_scale(K: int) -> float:
    # Must mirror the encoding used in main.py when saving predictions:
    return 63 if K == 5 else 255 / (K - 1)


def get_z(image: Path) -> int:
    return int(image.stem.split('_')[-1])


def inverse_pad_or_crop_center(img: np.ndarray, original_shape: tuple[int, int]) -> np.ndarray:
    """
    Reverses the pad_or_crop_center operation, placing a 256x256 prediction
    back into its original bounding canvas.
    """
    cx, cy = img.shape
    ox, oy = original_shape

    # X axis
    if ox > cx: # It was cropped down to 256. Pad it back out.
        start_x = (ox - cx) // 2
        res_x = np.zeros((ox, cy), dtype=img.dtype)
        res_x[start_x:start_x + cx, :] = img
    else: # It was padded up to 256. Crop it back down.
        start_x = (cx - ox) // 2
        res_x = img[start_x:start_x + ox, :]

    # Y axis
    if oy > cy:
        start_y = (oy - cy) // 2
        res = np.zeros((ox, oy), dtype=img.dtype)
        res[:, start_y:start_y + cy] = res_x
    else:
        start_y = (cy - oy) // 2
        res = res_x[:, start_y:start_y + oy]

    return res


def stitch_patient(id_: str, images: list[Path], dest_folder: Path,
                   K: int, source_pattern: str,
                   resample: bool = False,
                   target_spacing: tuple[float, float, float] = (1.0, 1.0, 2.5)) -> Path:

    ct_nib = nib.load(source_pattern.format(id_=id_))
    X, Y, Z = ct_nib.shape
    dx, dy, dz = ct_nib.header.get_zooms()[:3]

    # Calculate the shape of the volume generated by slice_segthor.py
    if resample:
        zoom_factors = (dx / target_spacing[0], dy / target_spacing[1], dz / target_spacing[2])
        RX = int(round(X * zoom_factors[0]))
        RY = int(round(Y * zoom_factors[1]))
        RZ = int(round(Z * zoom_factors[2]))
    else:
        RX, RY, RZ = X, Y, Z

    zs: list[int] = map_(get_z, images)
    assert len(images) == RZ, f"{id_}: {len(images)} slices found but expected {RZ} (resampled)"
    assert sorted(zs) == list(range(RZ)), f"{id_}: slice indices are not 0..{RZ - 1}"

    scale: float = label_scale(K)
    volume_resampled = np.zeros((RX, RY, RZ), dtype=np.uint8)

    for png, z in zip(images, zs):
        raw: np.ndarray = imread(png)
        labels = np.rint(raw / scale).astype(np.uint8)

        if resample:
            # Reverse the 256x256 crop/pad to get back to the pre-crop physical shape
            labels = inverse_pad_or_crop_center(labels, (RX, RY))
        else:
            if labels.shape != (RX, RY):
                labels = resize(labels, (RX, RY), order=0, mode="constant", preserve_range=True, anti_aliasing=False).astype(np.uint8)

        volume_resampled[:, :, z] = labels

    # Reverse the Z-axis (and X/Y) resampling to get back to the original CT dimensions
    if resample:
        inverse_zoom = (X / RX, Y / RY, Z / RZ)
        # order=0 is mandatory to prevent class labels from interpolating into non-existent classes
        volume = scipy.ndimage.zoom(volume_resampled, inverse_zoom, order=0, mode='nearest')
    else:
        volume = volume_resampled

    assert volume.shape == ct_nib.shape, f"Shape mismatch: restored {volume.shape}, original {ct_nib.shape}"
    assert set(np.unique(volume)) <= set(range(K)), np.unique(volume)

    out_nib = nib.nifti1.Nifti1Image(volume, affine=ct_nib.affine, header=ct_nib.header)
    out_nib.set_data_dtype(np.uint8)
    out_path: Path = (dest_folder / id_).with_suffix(".nii.gz")
    nib.save(out_nib, str(out_path))

    return out_path


def group_by_patient(images: list[Path], grp_regex: str) -> dict[str, list[Path]]:
    pattern: Pattern = re.compile(grp_regex)

    groups: dict[str, list[Path]] = {}
    for image in images:
        match: Match | None = pattern.match(image.stem)
        assert match is not None, f"{image.stem} does not match {grp_regex}"
        groups.setdefault(match.group(1), []).append(image)

    for id_, files in groups.items():
        files.sort(key=get_z)

    assert sum(len(v) for v in groups.values()) == len(images)
    return groups


def main(args: argparse.Namespace) -> None:
    images: list[Path] = sorted(Path(args.data_folder).glob("*.png"))
    assert len(images) > 0, f"No .png found in {args.data_folder}"

    groups: dict[str, list[Path]] = group_by_patient(images, args.grp_regex)
    ids: list[str] = sorted(groups.keys())
    print(f"Found {len(ids)} patients out of {len(images)} images ; regex: {args.grp_regex}")
    print(ids)

    args.dest_folder.mkdir(parents=True, exist_ok=True)

    pfun = partial(stitch_patient,
                   dest_folder=args.dest_folder,
                   K=args.num_classes,
                   source_pattern=args.source_scan_pattern,
                   resample=args.resample,
                   target_spacing=tuple(args.target_spacing))

    jobs: list[tuple[str, list[Path]]] = [(id_, groups[id_]) for id_ in ids]

    outputs: list[Path]
    match args.process:
        case 1:
            outputs = [pfun(id_, files) for id_, files in tqdm_(jobs)]
        case -1:
            outputs = Pool().starmap(pfun, jobs)
        case _ as p:
            outputs = Pool(p).starmap(pfun, jobs)

    print(f"Saved {len(outputs)} volumes to {args.dest_folder}")


def get_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description='Stitch 2D .png predictions back into 3D NIfTI volumes')
    parser.add_argument('--data_folder', type=Path, required=True,
                        help="Folder containing the predicted .png slices, e.g. results/X/best_epoch/val")
    parser.add_argument('--dest_folder', type=Path, required=True,
                        help="Where to write the Patient_XX.nii.gz volumes")
    parser.add_argument('--source_scan_pattern', type=str, required=True,
                        help="Pattern of the original CT scan, with {id_} as placeholder, e.g. 'data/segthor_part1/train/{id_}/{id_}.nii.gz'.")
    parser.add_argument('--grp_regex', type=str, default=r"(Patient_\d+)_\d+",
                        help="Regex on the .png stem whose first group is the patient id")
    parser.add_argument('--num_classes', '-K', type=int, default=5,
                        help="Number of classes K (including background) used to encode the .png")
    parser.add_argument('--process', '-p', type=int, default=1,
                        help="Number of processes (1: sequential, -1: all cores)")
    parser.add_argument('--resample', action='store_true',
                        help="Enable inverse physical resampling from target spacing.")
    parser.add_argument('--target_spacing', type=float, nargs=3, default=[1.0, 1.0, 2.5],
                        help="Target physical spacing (x, y, z) in mm. Used if --resample is set.")

    args = parser.parse_args()
    print(args)

    return args


if __name__ == "__main__":
    main(get_args())
