dataset: "SEGTHOR"
mode: "full"
K: 5
net_name: "ENet"
B: 8
kernels: 8
factor: 2
lr: 0.001
betas: [0.9, 0.999]
epochs: 25
num_workers: 5
temperature: 1.0
optimizer: "Adam"
seed: 123
patience: -1
loss_fn: "focal_dice"
focal_gamma: 1.5
