#!/bin/bash
# 5-fold cross-validation of the three final U-Nets (E_F05 2.5D, E_F06 2D, E_F07 3D) on
# one local GPU. Every fold: train on data/SEGTHOR_FULL_huwide_resampled_cv<k> (32 train /
# 8 val, folds from configs/splits/segthor_full_cv5_f<k>.json, fold 0 = the fixed 32/8
# split), infer the fold's val patients with lastweights.pt (final epoch, so the score is
# not biased by checkpoint selection), apply the final post-processing, score 3D metrics,
# and write those scores to the fold's W&B run (training curves are logged by the trainers).
#
# Usage, from the repo root:
#   scripts/run_cv5.sh --make-configs          # (re)write configs/cv5/ from configs/full/
#   scripts/run_cv5.sh -j 2 [JOB ...]          # run jobs, 2 at a time (default: all 15)
# A JOB is <config stem>, e.g. E_F05_unet25d_adamw_cosine_150ep_f3. Finished jobs (their
# eval/pp_final/metrics exists) are skipped, so the script can simply be rerun after a crash;
# 3D jobs resume from checkpoint.pt. E_F07 fold 0 reuses results/full/E_F07_unet3d_adamw_cosine
# (same split and code; its checkpoint.pt holds the final epoch 299) instead of retraining.
#
# Concurrency (A100 80GB, 2.5D training loop with -O): 1 job 195 slices/s, 2 jobs 111 each
# (222 total, +14%), 3 jobs 76 each (227 total). The GPU saturates at 2: use -j 2.
set -euo pipefail
PY=${PY:-.venv/bin/python}
BASES=(E_F07_unet3d_adamw_cosine E_F05_unet25d_adamw_cosine_150ep E_F06_unet2d_adamw_cosine_150ep)
OUT=results/cv5
MET_ARGS=(--gt_pattern 'data/segthor_train_full/train/{id_}/GT.nii.gz'
          --scan_pattern 'data/segthor_train_full/train/{id_}/{id_}.nii.gz'
          --class_names background esophagus heart trachea aorta --process 8)

make_configs() {
  mkdir -p configs/cv5
  for base in "${BASES[@]}"; do
    for k in 0 1 2 3 4; do
      {
        echo "# 5-fold CV, fold $k (data/SEGTHOR_FULL_huwide_resampled_cv$k = configs/splits/segthor_full_cv5_f$k.json)."
        echo "# Identical to configs/full/$base.yaml except dataset, run name, cv5/fold tags and PNG interval;"
        echo "# scored on lastweights.pt (final epoch), not bestweights.pt. Generated by scripts/run_cv5.sh --make-configs."
        sed -e "s|^dataset: .*|dataset: \"SEGTHOR_FULL_huwide_resampled_cv$k\"|" \
            -e "s|^wandb_run_name: .*|wandb_run_name: \"${base}_f$k\"|" \
            -e "s|^\(wandb_tags: \[.*\)\]|\1, \"cv5\", \"fold$k\"]|" "configs/full/$base.yaml"
        [[ $base == *unet3d* ]] || echo "save_val_png_every: 0"
      } > "configs/cv5/${base}_f$k.yaml"
    done
  done
  echo "wrote $(ls configs/cv5 | wc -l) configs to configs/cv5/"
}

run_job() {
  local exp=$1
  local config=configs/cv5/$exp.yaml dest=$OUT/$exp
  local k=${exp##*_f} dataset
  dataset=SEGTHOR_FULL_huwide_resampled_cv$k
  [ -f "$config" ] || { echo "no $config" >&2; return 1; }
  if [ -f "$dest/eval/pp_final/metrics/dice.npz" ]; then echo "[$(date '+%a %H:%M')] skip $exp (done)"; return 0; fi
  mkdir -p "$dest"
  echo "[$(date '+%a %H:%M')] start $exp (commit $(git rev-parse --short HEAD))"

  if [[ $exp == *unet3d* ]]; then
    if [[ $k == 0 && -f results/full/E_F07_unet3d_adamw_cosine/checkpoint.pt && ! -f $dest/lastweights.pt ]]; then
      cp results/full/E_F07_unet3d_adamw_cosine/config_dump.yaml "$dest/"
      $PY -c "import torch,sys; c=torch.load(sys.argv[1], map_location='cpu', weights_only=False); \
assert c['epoch'] == 299, c['epoch']; torch.save(c['net'], sys.argv[2])" \
        results/full/E_F07_unet3d_adamw_cosine/checkpoint.pt "$dest/lastweights.pt"
      echo "reused results/full/E_F07_unet3d_adamw_cosine (final epoch 299)" > "$dest/REUSED"
    fi
    [ -f "$dest/lastweights.pt" ] || \
      $PY -u train3d.py --config "$config" --dest "$dest" --gpu --resume > "$dest/train.log" 2> "$dest/train.err"
    $PY -u infer3d.py --config "$dest/config_dump.yaml" --weights "$dest/lastweights.pt" --gpu \
      --img_folder "data/$dataset/val/img" --dest "$dest/eval" \
      --scan_pattern 'data/segthor_train_full/train/{id_}/{id_}.nii.gz' > "$dest/infer.log" 2>&1
  else
    if [ ! -f "$dest/lastweights.pt" ]; then
      $PY -u scripts/preflight_segthor.py --config "$config" > "$dest/preflight.log" 2>&1
      # -O: skip the per-iteration debug asserts (torch.unique on every batch, ~7x slower)
      $PY -O -u main.py --config "$config" --dest "$dest" --gpu > "$dest/train.log" 2> "$dest/train.err"
    fi
    # The dataset's preprocess.json makes infer.py / infer3d.py undo the resampling when stitching
    $PY -u infer.py --config "$dest/config_dump.yaml" --weights "$dest/lastweights.pt" --gpu \
      --img_folder "data/$dataset/val/img" --dest "$dest/eval" \
      --scan_pattern 'data/segthor_train_full/train/{id_}/{id_}.nii.gz' > "$dest/infer.log" 2>&1
  fi

  $PY postprocess.py --input_folder "$dest/eval/nii" --output_folder "$dest/eval/pp_final/nii" \
    --lcc 2 3 --min_ml 4:1 --process 8 > "$dest/eval/pp_final.log" 2>&1
  for d in "$dest/eval" "$dest/eval/pp_final"; do
    $PY metrics3d.py --pred_folder "$d/nii" --dest "$d/metrics" "${MET_ARGS[@]}" > "$d/metrics.log" 2>&1
  done
  # Final CV scores into the fold's W&B run summary (cv/raw/*, cv/pp/*); never fails the job
  $PY scripts/cv5_to_wandb.py --dest "$dest" > "$dest/wandb_summary.log" 2>&1 || echo "W&B summary failed for $exp (see $dest/wandb_summary.log)"
  echo "[$(date '+%a %H:%M')] done $exp"
}

if [[ ${1:-} == --make-configs ]]; then make_configs; exit 0; fi
J=1
if [[ ${1:-} == -j ]]; then J=$2; shift 2; fi
JOBS=("$@")
if [ ${#JOBS[@]} -eq 0 ]; then
  for base in "${BASES[@]}"; do for k in 0 1 2 3 4; do JOBS+=("${base}_f$k"); done; done
fi
mkdir -p "$OUT"
for exp in "${JOBS[@]}"; do
  while [ "$(jobs -rp | wc -l)" -ge "$J" ]; do wait -n || true; done
  ( run_job "$exp" || echo "[$(date '+%a %H:%M')] FAILED $exp (see $OUT/$exp/*.err / *.log)" ) &
done
wait
echo "[$(date '+%a %H:%M')] all jobs finished"
