# P_E008.1_alphafocal_mild_gamma1_lr_0.001.yaml
dataset: "SEGTHOR"
mode: "full"
K: 5
net_name: "ENet"
B: 8
kernels: 8
factor: 2
lr: 0.002
betas: [0.9, 0.999]
epochs: 25
num_workers: 5
temperature: 1.0
optimizer: "Adam"
seed: 123
patience: -1
loss_fn: "focal"
focal_gamma: 1.0
